configure: more user-friendly macOS checks
When linking with /usr/local/lib/libomp.dylib and not -lomp, warn about
the potential incompatibility. When all tests fail, suggest downloading
the OpenMP runtime and headers.

In addition to R CMD SHLIB --preclean, explicitly remove the shared
library from the previous iteration. Otherwise Make may keep the stale
file due to the new object file being compiled in the same second as the
old shared library, failing subsequent tests.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -14,6 +14,51 @@ log () {
 
 test_openmp () {
 	log "* checking if OpenMP works with CFLAGS=%s LIBS=%s... " "$1" "$2"
+	# --preclean is not enough; remove the DLL too
+	# otherwise Make may assume that the same-second object file is not newer than the previously built DLL
+	"${R_HOME}"/bin/Rscript -e 'unlink(paste0("test", .Platform$dynlib.ext))'
+
+	if ! PKG_CFLAGS="$1" PKG_LIBS="$2" "${R_HOME}"/bin/R CMD SHLIB --preclean --clean test.c >>config.log 2>&1; then
+		log "failed to build\n"
+		return 1
+	fi
+
+	if ! "${R_HOME}"/bin/Rscript -e '
+dll <- paste0("test", .Platform$dynlib.ext)
+dyn.load(dll)
+ans <- .C("test_openmp", ans = integer(1))$ans
+stopifnot(identical(ans, 3L))
+' >> config.log 2>&1; then
+		log "failed to run\n"
+		return 1
+	fi
+
+	OMP_CFLAGS="$1"
+	OMP_LIBS="$2"
+	log "yes\n"
+	return 0
+}
+
+guess_openmp_macos () {
+	test_openmp "-Xclang -fopenmp" "-lomp" \
+	|| \
+	test_openmp '$(SHLIB_OPENMP_CFLAGS)' '$(SHLIB_OPENMP_CFLAGS)' \
+	&& return
+
+	if test_openmp "-Xclang -fopenmp" "/usr/local/lib/libomp.dylib"; then
+		log "Since an earlier test for -lomp failed, the resulting package is probably unsafe to mix with CRAN binaries!\n"
+		return
+	fi
+
+	log "Couldn't guess a working OpenMP configuration.\n"
+	log "Do you need an OpenMP runtime and headers from <https://mac.r-project.org/openmp/>?\n"
+	OMP_CFLAGS=""
+	OMP_LIBS=""
+}
+
+case "$(uname)" in
+Darwin)
+	log "Guessing OpenMP configuration for macOS\n"
 	cat >"test.c" <<'EOF'
 #ifdef _OPENMP
 #include <omp.h> /* Sometimes the runtime is fine, but there's no header. */
@@ -29,35 +74,7 @@ void test_openmp(int * result) {
  *result = sum;
 }
 EOF
-	if ! PKG_CFLAGS="$1" PKG_LIBS="$2" "${R_HOME}"/bin/R CMD SHLIB --preclean --clean test.c >>config.log 2>&1; then
-		log "no\n"
-		return 1
-	fi
-	rm -f test.c
-
-	if ! "${R_HOME}"/bin/Rscript -e '
-dll <- paste0("test", .Platform$dynlib.ext)
-dyn.load(dll)
-ans <- .C("test_openmp", ans = integer(1))$ans
-stopifnot(identical(ans, 3L))
-' >> config.log 2>&1; then
-		log "no\n"
-		return 1
-	fi
-
-	OMP_CFLAGS="$1"
-	OMP_LIBS="$2"
-	log "yes\n"
-	return 0
-}
-
-case "$(uname)" in
-Darwin)
-	log "Guessing OpenMP configuration for macOS\n"
-	test_openmp '$(SHLIB_OPENMP_CFLAGS)' '$(SHLIB_OPENMP_CFLAGS)' || \
-	test_openmp "-Xclang -fopenmp" "-lomp" || \
-	test_openmp "-Xclang -fopenmp" "/usr/local/lib/libomp.dylib" || \
-	{ OMP_CFLAGS=""; OMP_LIBS=""; }
+	guess_openmp_macos
 	rm -f test.*
 	;;
 *)
